### ISSUE TITLE
How do I disable SSL in production with this gem?

### ISSUE THREAD

**Issue by thelinuxlich** [spree-contrib/spree_shared#5]
It seems that the stores ignore the config/initializers/spree.rb statement of "config.allow_ssl_in_production = false"

**Comment by martonpe** [comment]
@JDutil Even though this issue is more a question that an issue, I think this would warrant a bit of explanation in the README. 
I ran into something similar, where settings from the initializers were not inserted to the DB with the correct key, because the monkey patching of `Spree::Preferences::ScopedStore` only gets loaded later in the lifecycle, hence the tenant was missing from the beginning of the key. You mention, that settings should not be set in initializers, but then where? I think a little note about this should be added to the README. My workaround is that I created a rake task for the settings, but then it's just that: a workaround.

**Comment by JDutil** [comment]
Not sure why I was talking against it being in an initializer that should be fine, but you can't do it in the spree.rb Spree.config block because that isn't working with apartment:
```
Spree.config do |config|
  # Example:
  # Uncomment to override the default site name.
  # config.site_name = "Spree Demo Site"
end
```

What we do is in the spree.rb initializer, but you have to iterate through each of your stores so for example it would look like this:
```
STORES.each do |store, config|
  begin
    Apartment::Database.switch store

    Spree::Wombat::Config.push_objects = ["Spree::Order", "Spree::Product", "Spree::Shipment", "Spree::StockItem"]

    Spree::Wombat::Config.payload_builder = {
      "Spree::Order" => {
        :serializer => "Spree::Wombat::OrderSerializer",
        :root => "orders",
        :filter => "complete"
      },
      "Spree::Product" => {
        :serializer => "Spree::Wombat::ProductSerializer",
        :root => "products"
      },
      "Spree::Shipment" => {
        :serializer => "SandboxShipmentSerializer",
        :root => "shipments"
      },
      "Spree::StockItem" => {
        :serializer => "Spree::Wombat::StockItemSerializer",
        :root => "inventories"
      }
    }

    Spree::Wombat::Config.connection_token = config[:token]
    Spree::Wombat::Config.connection_id = config[:id]

    Spree::Config.auto_capture = true
  rescue
    puts "  Failed to set up Wombat config for store '#{store}'"
  end
end
```

Will add an example to readme.

**Comment by JDutil** [comment]
https://github.com/spree-contrib/spree_shared/commit/2857f2391118a1a719648bf44b082f65e20b560d
